import React, { PureComponent } from 'react'
import styles from './protocol.less'

export default class ProtocolEnglish extends PureComponent {
  render() {

    return (
      <div className={styles.protocol}>
        <div className={styles.content}>
          <h2>User Agreement</h2>
          <p>crebe is a future-oriented digital currency and digital asset circulation trading community, which website “https://www.crebe.com” (hereinafter referred to as 'this Website' or 'the Website') is a platform dedicated to the transaction of digital assets and the provision of related services (hereinafter referred to as 'the Service'). For the convenience of wording in this Agreement, the Company and the Website are referred to as 'We' or other applicable forms of first person pronouns in this Agreement. All natural persons or other subjects who log onto this Website shall be users of this Website. For the convenience of wording in this Agreement, the users are referred to as 'You' or any other applicable forms of the second-person pronouns. For the convenience of wording in this Agreement, you and us are collectively referred to as “both parties”, and individually as “one party”.</p>
          <h3>Important reminder:</h3>
          <p>1.The digital assets themselves are not offered by any financial institution, corporation or this Website. The digital asset market is new and unconfirmed, and will not necessarily expand;</p>
          <p>2.Digital asset transactions are highly risky, due to the fact that they are traded throughout 24-hour a day without limits on the rise or fall in price;</p>
          <p>3.Digital asset transactions may be suspended or prohibited at any time due to the enactment or modification of national laws, regulations and regulatory documents.</p>
          <p>Digital assets trading is highly risky and therefore not suitable for the vast majority of people. You acknowledge and understand that investment in digital assets may result in partial or total loss of your investment and therefore you are advised to decide the amount of your investment on the basis of your loss-bearing capacity. Furthermore, aside from the above-mentioned risks, there may also be unpredictable risks. Therefore, you are advised to carefully consider and use clear judgment to assess your financial position and the abovementioned risks before making any decisions on buying and selling digital assets; any and all losses arising therefrom will be borne by you and we shall not be held liable in any manner whatsoever.</p>

          <h3>Ⅰ.The General</h3>
          <p>1.1 Before using the services provided by this website, you should read this agreement carefully. If you do not understand or need to, please consult a professional lawyer. If you do not agree to this agreement and/or amend it at any time, please stop using the services provided by this website immediately or stop landing on this website. Once you log on to this website, use any service of this website or any other similar act, you are fully aware of and agree with the contents of this agreement, including any modifications made by this website at any time to this agreement. </p>
          <p>1.2 You can become a member of this website (hereinafter referred to as "member") by filling in relevant information according to the requirements of this website and successfully registering after other relevant procedures. Clicking the "agree" button in the process of registration means that you have reached an agreement with the company in the form of electronic signature; or you are in the process of using this website. Clicking on any button marked with "consent" or similar meaning or actually using the services provided by this website in other ways permitted by this website means that you fully understand, agree to and accept all the terms and conditions of this agreement. Without your written signature, this agreement is not legally binding on you. What impact? </p>
          <p>1.3 After you become a member of this website, you will get a member account and corresponding password, which will be kept by the member, and the member shall be liable for all activities and incidents with your account number. </p>
          <p>14.By registering and using any services and functions provided by this website, you will be deemed to have read, understood and accepted the following terms:</p>
          <p>1.4.1 Subject to all terms and conditions of this Agreement. </p>
          <p>1.4.2 You confirm that you have reached the legal age required by different applicable laws to enter into contracts and are fully capable of accepting these terms.</p>
          <p>1.4.3 You guarantee that all the digital assets involved in the transaction that belong to you are legally acquired and owned. </p>
          <p>1.4.4 You agree to assume full responsibility for your own trading or non-trading activities and any gains or losses. </p>
          <p>1.4.5 You confirm that the information provided at the time of registration is true and accurate. </p>
          <p>1.4.6 You agree to abide by the provisions of any relevant laws, including the reporting of any transaction profits for tax purposes. </p>
          <p>1.4.7 This Agreement only restricts the rights and obligations between you and us, and does not involve legal relations and disputes arising from the transaction of digital assets between users of this website and other websites or between you. </p>
          <h3>II. Agreement revision </h3>
          <p>We reserve the right to amend this Agreement from time to time, and to announce it by way of website publicity, without notifying you separately. The changed agreement will mark the time of change on the front page of this agreement, and will take effect automatically once it is published on the website. You should browse and pay attention to the update time and content of this agreement from time to time. If you do not agree with the relevant changes, you should immediately stop using this website service. If you continue to use this website service, you will accept and agree to the constraints of the revised agreement.</p>
          <h3>Ⅲ. Registration </h3>
          <p>3.1 Registration qualification </p>
          <p>You confirm and promise that when you complete the registration procedure or actually use the services provided by this website in other ways permitted by this website, you shall be a natural person, legal person or other organization with the ability to sign this Agreement and use the services provided by this website as required by applicable law. Once you click the "Agree to Register" button, it means that you or your authorized agent have agreed to the content of the agreement and registered and used the website service by its agent. If you do not have the above subject qualification, you and your authorized agent shall bear all the consequences arising therefrom, and the company reserves the right to cancel or permanently freeze your account and to hold you and your authorized agent accountable. </p>
          <p>3.2 Registration purposes </p>
          <p>You confirm and promise that your registration of this website is not for the purpose of violating laws and regulations or disrupting the order of digital assets transactions on this website. </p>
          <p>3.3 Registration process </p>
          <p>3.3.1 You agree to provide effective e-mail, mobile phone number and other information according to the requirements of the user registration page of this website. You can use the email, mobile phone number provided or confirmed by you or other ways allowed by this website to access this website as a means of landing. If necessary, in accordance with the relevant laws and regulations in different jurisdictions, you must provide your real name, identity documents and other laws and regulations as well as privacy provisions and anti-money laundering provisions of the relevant information and constantly update the registration data, in line with timely, detailed and accurate requirements. All original typed data will be referenced as registration data. You shall be responsible for the authenticity, completeness and accuracy of such information and bear any direct or indirect losses and adverse consequences arising therefrom. </p>
          <p>3.3.2 If the laws and regulations, rules and orders of your sovereign country or region require the real name of the mobile phone number, you agree that the registration of the mobile phone number is registered by the real name. If you do not provide it in accordance with the regulations, any direct or indirect losses and adverse consequences will be borne by you. </p>
          <p>3.3.3 You have the right to obtain the account and password of this website. When you get the account and password of this website, you will be regarded as successful in registration. You can login on this website for members. </p>
          <p>3.3.4 You agree to receive e-mails and/or short messages sent by this website related to the management and operation of this website.</p>
          <h3>IV, Service </h3>
          <p>This website only provides online trading platform services for your digital assets trading activities (including but not limited to digital assets trading services) through this website. This website does not participate in the buying and selling of digital assets as a buyer or seller. </p>

          <p>4.1 Service content </p>
          <p>4.1.1 You have the right to browse the real-time market and trading information of digital assets products on this website, and to submit the digital assets trading instructions and complete the digital assets trading through this website. </p>
          <p>4.1.2 You have the right to participate in the website activities organized by this website in accordance with the rules of activities published by this website. </p>
          <p>4.1.3 This website promises to provide you with other services. </p>
          <p>4.2. Service rules </p>
          <p>You promise to abide by the following rules of this website: </p>
          <p>4.2.1 You shall abide by the laws, regulations and policy requirements to ensure the legitimacy of all sources of digital assets in your account. You shall not engage in illegal or other activities that damage the rights and interests of this website or third parties by using the services of this website, such as sending or receiving any illegal, illegal or infringing activities on the rights and interests of others. Information, sending or receiving pyramid selling materials or other harmful information or speech, using or forging the header information of e-mail of this website without authorization of this website, etc. </p>
          <p>4.2.2 You should abide by laws and regulations and properly use and maintain the account number and login password, capital password, and the mobile phone number bound at the time of registration, as well as the security of the mobile phone authentication code received by the mobile phone. You are fully responsible for any operation and consequences of using your website account and login password, capital password and mobile phone verification code. When you find that the account number, login password, capital password,authentication code are used by unauthorized third parties, or there are other account security problems, you should immediately and effectively notify the website and request the website to suspend the service of the account number of this website. This website has the right to act on your requests within a reasonable time, but it is not liable for any consequences (including but not limited to any loss) that have occurred before the action is taken. You may not give, borrow, rent, transfer or otherwise dispose of the account of this website without the consent of this website.  </p>
          <p>4.2.3 You agree that you are liable for all activities under your website's account and password (including but not limited to information disclosure, information publication, online click agreement or submission of various rule agreements, online renewal agreements or purchase services, etc.).</p>
          <p>4.2.4 You shall not maliciously interfere with the normal operation of digital assets transactions and disrupt the order of transactions while doing digital assets transactions on this website; you shall not interfere with the normal operation of this website or interfere with other users'use of this website services by any technical means or other means; you shall not maliciously defame this website by means of fictitious facts, etc. Goodwill. </p>
          <p>4.2.5 If you have disputes with other users due to online transactions, you may not request relevant information from this website through judicial or administrative channels. </p>
          <p>4.2.6 In the course of using the services provided by this website, you will bear the tax payable, as well as all hardware, software, services and other expenses. </p>
          <p>4.2.7 You shall abide by this Agreement and other terms and conditions of service and rules of operation which are published and updated from time to time by this website, and have the right to terminate the use of the services provided by this website at any time. </p>
          <p>4.3. product rules </p>
          <p>4.3.1 Currency Trading Product Rules </p>
          <p>You promise to abide by the following rules in the course of entering this website and trading currency with other users through this website. </p>
          <p>4.3.1.1 Browse Transaction Information </p>
          <p>When you browse currency trading information on this website, you should carefully read all the contents contained in the trading information, including but not limited to price, Commission volume, handling fee, purchase or sale direction. You can click the button after you fully accept all the contents contained in the trading information. </p>
          <p>4.3.1.2 submission of entrustment </p>
          <p>After browsing the transaction information and confirming it is correct, you can submit the transaction commission. After you submit the transaction commission, you authorize this website to act as your agent for the corresponding transaction matching. This website will automatically complete the matching transaction when there is a transaction that meets your commission price without prior notice. </p>
          <p>4.3.1.3 Check the transaction details </p>
          <p>You can check the corresponding transaction records in the transaction details of the management center to confirm your detailed transaction records. </p>
          <p>4.3.1.4 Revoke/modify the entrustment. You have the right to revoke or modify the entrustment at any time before the transaction is concluded. </p>
          <h3>V. Rights and Obligations </h3>
          <p>5.1 If you do not have the registration qualifications stipulated in this agreement, this website has the right to refuse you to register. For those registered, this website has the right to cancel your membership account. This website reserves the right to hold you or your authorized agent accountable. At the same time, this website reserves the right to decide whether to accept your registration under any other circumstances. </p>
          <p>5.2 This website has the right to suspend or terminate the use of an account when it finds that the account user is not the initial registrant of the account. </p>
          <p>5.3 This website has the right to notify you to correct, update or suspend or terminate the service provided by this website when it reasonably suspects that the information you provide is wrong, false, invalid or incomplete through technical testing and manual sampling. </p>
          <p>5.4 This website has the right to correct any information displayed on this website when it is found that there are obvious errors.</p>
          <p>5.5 This website reserves the right to modify, suspend or terminate the service of this website at any time without prior notice. If the website terminates one or more services of this website, the termination shall take effect on the day when the website publishes the termination announcement on the website. </p>
          <p>5.6 The website shall adopt necessary technical means and management measures to ensure the normal operation of the website, provide necessary and reliable trading environment and services, and maintain the order of digital assets trading. </p>
          <p>5.7 This website guarantees the security of your digital assets by strengthening technical input and enhancing security precautions. We are obliged to notify you in advance when there are foreseeable security risks in your account. </p>
          <p>5.8 This website has the right to provide you with more information or information according to the requirements of the laws, regulations, orders and other norms of your sovereign country or region, and take reasonable measures to meet the requirements of the local norms. You have the obligation to cooperate. This website has the right to comply with the laws of your sovereign country or region. As required by laws, rules, orders, etc., suspend or permanently suspend the opening of this website to you and part or all of its services.</p>
          <h3>VI. Compensation </h3>
          <p>6.1 Under no circumstances shall our liability for direct damage to you exceed the total cost of three (3) months incurred by you from using the services of this website. </p>
          <p>6.2 If you violate this Agreement or other laws and regulations, you must compensate us at least $2 million and bear all the costs (including attorney's fees) arising therefrom. If you do not make up for the actual losses, you must make up for them. </p>
          <h3>VII. Right to seek injunction relief </h3>
          <p>We and you acknowledge that common law remedies for breaches of contract or possible breaches may not be sufficient to compensate for all losses suffered by us. Therefore, non-breaching parties have the right to seek injunction remedies and all other remedies permitted by common law or equity in case of breaches or possible breaches of contract.</p>
          <h3>VIII. Limitation and Exemption of Liability</h3>
          <p>8.1 You understand and agree that under no circumstances shall we be liable for the following matters: </p>
          <p>8.1.1 Loss of revenue; </p>
          <p>8.1.2 Transaction profits or contract losses;</p>
          <p>8.1.3 business interruption </p>
          <p>8.1.4 Expected savings in monetary losses; </p>
          <p>8.1.5 Information loss; </p>
          <p>8.1.6 Loss of opportunity, goodwill or reputation;</p>
          <p>8.1.7 Damage or loss of data; </p>
          <p>8.1.8 The cost of purchasing alternative products or services; </p>
          <p>8.1.9 Any indirect, special or incidental loss or damage arising from infringement (including negligence), breach of contract or any other cause, whether or not such loss or damage can reasonably be foreseen by us, whether or not we have been informed in advance of the possibility of such loss or damage. </p>
          <p>Articles 8.1.1 to 8.1.9 are independent of each other. </p>
          <p>8.2 You understand and agree that we are not liable for any damages caused to you by any of the following circumstances: </p>
          <p>8.2.1 We have reasonable grounds to believe that there may be major violations or breaches of contract in your specific transaction. </p>
          <p>8.2.2 We have reasonable reasons to believe that your actions on this website are suspected of being illegal or improper. </p>
          <p>8.2.3 Costs and losses incurred by the purchase or acquisition of any data, information or transaction or substitution through the services of this website.</p>
          <p>8.2.4 Your misunderstanding of this website service. </p>
          <p>8.2.5 Any other loss related to the services provided by this website that is not caused by us. </p>
          <p>8.3 We deal with such problems as maintenance of information network equipment, failure of information network connection, failure of computers, communications or other systems, power failure, weather causes, accidents, strikes, labor disputes, riots, uprisings, riots, insufficient productivity or means of production, fires, floods, storms, explosions, wars, banks or We will not be liable for any other reasons, such as the collapse of the digital asset market, government actions, orders of judicial or administrative organs, non-service or delayed service caused by other acts beyond our control or by acts beyond our control or by third parties, as well as your losses. </p>
          <p>8.4 We cannot guarantee the complete security of all information, programs, texts and so on contained in this website, and are not disturbed and destroyed by any malicious programs such as viruses and Trojans. Therefore, it is your personal decision to log in, use any services of this website or download and use any programs, information and data downloaded by this website. Risk and possible loss. </p>
          <p>8.5 We do not guarantee or commit to any information, products and business of any third party website linked to this website or any other form of content that does not belong to our main body. If you use any services, information and products provided by the third party website, you will personally decide and bear the resulting one. Cut responsibility. </p>
          <p>8.6 8.6 We do not provide any express or implied guarantee for your use of this website service, including, but are not limited to, the applicability, absence of errors or omissions, continuity, accuracy, reliability and applicability of the services provided by this website for a specific purpose. At the same time, we do not make any commitment and guarantee to the validity, accuracy, correctness, reliability, quality, stability, integrity and timeliness of the technology and information involved in the services provided by this website. Whether or not to log in or use the services provided by this website is your personal decision and take risks and possible losses on your own. We do not guarantee the market, value and price of digital assets. You understand and understand that the market of digital assets is unstable. Prices and values will fluctuate or collapse at any time. Transaction of digital assets is your own free choice and decision, and you will bear risks and possible losses. </p>
          <p>8.7 The guarantees and commitments stipulated in this Agreement are the sole guarantees and statements of our services under this Agreement and this Website, and replace any other guarantees and commitments arising from any other means or means, whether written or oral, express or implied. All these guarantees and statements represent only our own commitments and guarantees and do not guarantee any third party to abide by the guarantees and commitments contained in this Agreement. </p>
          <p>8.8 We shall not waive any right not mentioned in this Agreement to limit, exempt or offset our liability for damages to the maximum extent applicable by law.</p>
          <p>8.9 Upon registration, you acknowledge that any operation we perform in accordance with the rules set forth in this Agreement will entail any risk to you.</p>

          <h3>Ⅸ.Termination of Agreement </h3>
          <p>9.1 This website has the right to cancel your account in accordance with this agreement. This agreement terminates on the date of account cancellation. </p>
          <p>9.2 This Website has the right to terminate all services of this Website in accordance with this Agreement. This Agreement shall terminate on the date of termination of all services of this Website. </p>
          <p>9.3 After the termination of this Agreement, you shall not be entitled to request the Website to continue to provide any services or perform any other obligations to it, including, but not limited to, requesting the Website to retain or disclose to you any information in its original website account, to forward to you or a third party any information it has not read or sent, etc. </p>
          <p>9.4 The termination of this Agreement shall not affect the obligation of the breaching party to demand other liabilities.</p>
          <h3>X.Intellectual Property Rights </h3>
          <p>10.1 All intellectual achievements contained in this website include, but are not limited to, website logos, databases, website design, text and graphics, software, photographs, videos, music, sound and their combination mentioned above. The intellectual property rights of software compilation, related source codes and software (including small applications and scripts) are vested in this website. Yes. You may not copy, modify, copy, send or use any of the aforementioned materials or contents for commercial purposes. </p>
          <p>10.2 All rights contained in the name of this website (including but not limited to goodwill, trademarks and logos) shall be owned by the company. </p>
          <p>10.3 Your acceptance of this Agreement shall be deemed to be the copyright of any form of information published on this website on your own initiative, including, but not limited to, copyright, distribution right, lease right, exhibition right, performance right, projection right, broadcasting right, information network dissemination right, production right, adaptation right, translation right, compilation right and the right to be published by the author. The other transferable rights enjoyed by the owner are transferred to the website exclusively and gratuitously. The website has the right to sue separately for any subject's infringement and obtain full compensation. The validity of this Agreement shall extend to any copyright law-protected content you publish on this website, whether formed before or after the signing of this Agreement. </p>
          <p>10.4 You may not illegally use or dispose of the intellectual property rights of this website or others in the course of using this website service. You may not publish or authorize other websites (and media) to use information already published on this website in any form. </p>
          <p>10.5 Your access to this website or any services provided by this website shall not be deemed to be our transfer of any intellectual property rights to you.</p>
          <h3>Ⅺ.Others </h3>
          <p>11.1 Divisibility </p>
          <p>If any provision of this Agreement is deemed unenforceable, invalid or illegal by any court having jurisdiction, it shall not affect the validity of the remaining provisions of this Agreement.</p>
          <p>11.2 Non agency relationship </p>
          <p>Nothing in this Agreement shall be deemed to have created, implied or otherwise treated as your agent, trustee or other representative, except as otherwise provided in this Agreement.</p>
          <p>11.3 Abstaining</p>
          <p>The waiver by either party of us or you of the liability for breach of contract or other liabilities stipulated in this Agreement shall not be deemed or interpreted as a waiver of other liabilities for breach of contract; failure to exercise any right or relief shall not in any way be interpreted as a waiver of such rights or relief. </p>
          <p>11.4 Title </p>
          <p>All titles are for the convenience of the agreement and are not intended to expand or limit the content or scope of the terms of the agreement. </p>
          <h3>XII. Effectiveness and Interpretation </h3>
          <p>12.1 This Agreement shall take effect when you click on the registration page of this website and complete the registration procedure and obtain the account and password of this website. It is binding on this website and you. </p>
          <p>12.2 The right of final interpretation of this Agreement shall be vested in this website.</p>
        </div>
      </div>
    )
  }
}